import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import sanitizeHtml from "sanitize-html";
const inter = Inter({ subsets: ['latin'] })
const htmlString = `
<div>Новый текст</div>
`

const copyToClipboard = ( text: string) =>{
  navigator.clipboard.writeText(text)
  .catch((error) => {
    console.error("Error copying text to clipboard:", error);
  });
}

export default function Home() {
  const sanitizedHtml = sanitizeHtml(htmlString);
  
  return (
    <>
      <Head>
        <title>Index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div dangerouslySetInnerHTML={{ __html: sanitizedHtml }} />
        <button onClick={(e)=>{copyToClipboard(htmlString)}}>Копировать в буфер обмена</button>
        <code>
          <pre>
            <div dangerouslySetInnerHTML={{ __html: sanitizedHtml }} />
          </pre>
        </code>
      </main>
    </>
  )
}
